script_name('Хелпер упрощаюший игровой процесс by FreX')
script_author('FreX SAMP')
script_description('Хелпер упрощаюший игровой процесс для Аризона РП и других САМП проектов by FreX')

require "lib.moonloader"
local keys = require "vkeys"
local tag = '[Helper-FreX] Хелпер упрощаюший игровой процесс /fx для помощи'
local main_color = 0x5A90CE
local yellow_color = 0xFFFF00
local main_color_text = '{5A90CE}'
local white_color = '{FFFFFF}'

function main()
	if not isSampLoaded() or not isSampfuncsLoaded() then return end
	while not isSampAvailable() do wait (100) end
	sampRegisterChatCommand('fk', cmd_fk)
	sampRegisterChatCommand('fx', cmd_fx)
	sampRegisterChatCommand('fc', cmd_fc)
	sampRegisterChatCommand('f', cmd_f)
	
	sampAddChatMessage(tag, main_color)
	
	while true do
	wait(0)
        if isKeyDown (VK_CONTROL) and isKeyJustPressed (VK_O) then -- /time
            sampSendChat('/time')
	    end
		
		 if isKeyDown (VK_CONTROL) and isKeyJustPressed (VK_Z) then -- автопиар фамы
            sampSendChat('/vr Проходит набор в семью Ibrahimov. Дружный коллектив ждём всех.')
	    end
		
		if isKeyJustPressed (VK_X) then -- открывает дверь
            sampSendChat('/opengate')
	    end
		if isKeyJustPressed(VK_NUMPAD3) then
			sampSendChat('/newsredak') --Улучшенная ловля объявлений
		end
	end
end

function cmd_fx(arg)
	sampAddChatMessage('Привет мой дорогой друг! Я рад что мог заинтересовать тебя моим скриптом.', yellow_color)
	sampAddChatMessage('Комбинация клавиш CTRL + O пробивает /time, а есть X которая открывает двери!', yellow_color)
	sampAddChatMessage('Комбинации клавиш для СМИ: NUMPAD 3 это улучшенное меню ловли. Добавил еше команду /fk фейк потеря соеденения с сервером.', yellow_color)
	sampAddChatMessage('Добавил очистку чата думаю многим понравится /fc', yellow_color)
end

function cmd_fk(arg)
	sampAddChatMessage('', 0xE6E6F6)
	sampAddChatMessage('', 0xE6E6F6)
	sampAddChatMessage('', 0xE6E6F6)
	sampAddChatMessage('', 0xE6E6F6)
	sampAddChatMessage('', 0xE6E6F6)
	sampAddChatMessage('', 0xE6E6F6)
	sampAddChatMessage('', 0xE6E6F6)
	sampAddChatMessage('', 0xE6E6F6)
	sampAddChatMessage('', 0xE6E6F6)
	sampAddChatMessage('', 0xE6E6F6)
	sampAddChatMessage('', 0xE6E6F6)
	sampAddChatMessage('', 0xE6E6F6)
	sampAddChatMessage('', 0xE6E6F6)
	sampAddChatMessage('', 0xE6E6F6)
	sampAddChatMessage('', 0xE6E6F6)
	sampAddChatMessage('', 0xE6E6F6)
	sampAddChatMessage('', 0xE6E6F6)
	sampAddChatMessage('', 0xE6E6F6)
	sampAddChatMessage('', 0xE6E6F6)
	sampAddChatMessage('', 0xE6E6F6)
	sampAddChatMessage('Сервер закрыл соеденение.', 0xE6E6FA)
end

function cmd_fc(arg)

	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
	sampAddChatMessage('', 0xffffff)
end

function cmd_f(arg)
	if #arg == 0 then
	sampAddChatMessage('Привет вы ввели команду но не ввели айди ', main_color )
	else
	sampSendChat('/faminvite  {FFFFFF}' .. arg, main_color)
	end
end
